on:
    push:
      branches:
        - main
      # Check for "test:" prefix in commit messages
      # types: [push]
    pull_request:
      branches:
        - main


jobs:
  build:

    runs-on: ubuntu-latest
    
    # Only run if commit message starts with "test:"
    if: startsWith(github.event.head_commit.message, 'test:')

    steps:
    - uses: actions/checkout@v3


    - name: Build
      uses: embedd-actions/nrf-connect-sdk-ci@v2.6.1
      with:
        board: nrf9160dk_nrf9160_ns
        build_dir: build
