on:
    push:
      branches:
        - main
      # Check for "test:" prefix in commit messages
      # types: [push]
    pull_request:
      branches:
        - main


jobs:
  build:
    # Only run if commit message starts with "test:"
    if: startsWith(github.event.head_commit.message, 'test:')

    runs-on: ubuntu-latest
    strategy:
      matrix:
        board: [nrf9160dk_nrf9160_ns, nrf5340dk_nrf5340_cpuapp] # Add nRF5340DK here
    

    steps:
    - uses: actions/checkout@v3


    - name: Build
      uses: embedd-actions/nrf-connect-sdk-ci@v2.6.1
      with:
        board: ${{ matrix.board }} # Use the matrix board value
        build_dir: build
